version: '3'
services:
  xpressengine:
    container_name: xpressengine
    build: .
    ports:
      - "4000:80"
    volumes:
      - "./flag:/flag:ro"
    depends_on:
      - db
  db:
    container_name: xpressengine-db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: xpressengine
      MYSQL_DATABASE: xpressengine
      MYSQL_USER: xpressengine
      MYSQL_PASSWORD: xpressengine
