version: '3'
services:
  www:
    container_name: marked
    image: node
    working_dir: /app
    command: sh -c "npm install && npm start"
    volumes:
      - "./app:/app"
      - "./flag:/flag:ro"
    depends_on:
      - "selenium"
    ports:
      - "3000:3000"
  selenium:
    container_name: marked-selenium
    image: selenium/standalone-chrome
    environment:
      GRID_TIMEOUT: 10
      SE_NODE_MAX_SESSIONS: 10
    volumes:
      - /dev/shm:/dev/shm
